# ConsoleFiler v${project.version} by novucs.

# RegEx console filters.
log-filters:
- "^(.*)(There are 0/40 players online:)(.*)$"
- "^(.*)(There are 1/40 players online:)(.*)$"
- "^(.*)(There are 2/40 players online:)(.*)$"
- "^(.*)(There are 3/40 players online:)(.*)$"
- "^(.*)(There are 4/40 players online:)(.*)$"
- "^(.*)(There are 5/40 players online:)(.*)$"
- "^(.*)(There are 6/40 players online:)(.*)$"
- "^(.*)(There are 7/40 players online:)(.*)$"
- "^(.*)(There are 8/40 players online:)(.*)$"
- "^(.*)(There are 9/40 players online:)(.*)$"
- "^(.*)(There are 10/40 players online:)(.*)$"
- "^(.*)(There are 11/40 players online:)(.*)$"
- "^(.*)(There are 12/40 players online:)(.*)$"
- "^(.*)(There are 13/40 players online:)(.*)$"
- "^(.*)(There are 14/40 players online:)(.*)$"
- "^(.*)(There are 15/40 players online:)(.*)$"
- "^(.*)(There are 16/40 players online:)(.*)$"
- "^(.*)(There are 17/40 players online:)(.*)$"
- "^(.*)(There are 18/40 players online:)(.*)$"
- "^(.*)(There are 19/40 players online:)(.*)$"
- "^(.*)(There are 20/40 players online:)(.*)$"
- "^(.*)(There are 21/40 players online:)(.*)$"
- "^(.*)(There are 22/40 players online:)(.*)$"
- "^(.*)(There are 23/40 players online:)(.*)$"
- "^(.*)(There are 24/40 players online:)(.*)$"
- "^(.*)(There are 25/40 players online:)(.*)$"
- "^(.*)(There are 26/40 players online:)(.*)$"
- "^(.*)(There are 27/40 players online:)(.*)$"
- "^(.*)(There are 28/40 players online:)(.*)$"
- "^(.*)(There are 29/40 players online:)(.*)$"
- "^(.*)(There are 30/40 players online:)(.*)$"
- "^(.*)(There are 31/40 players online:)(.*)$"
- "^(.*)(There are 32/40 players online:)(.*)$"
- "^(.*)(There are 33/40 players online:)(.*)$"
- "^(.*)(There are 34/40 players online:)(.*)$"
- "^(.*)(There are 35/40 players online:)(.*)$"
- "^(.*)(There are 36/40 players online:)(.*)$"
- "^(.*)(There are 37/40 players online:)(.*)$"
- "^(.*)(There are 38/40 players online:)(.*)$"
- "^(.*)(There are 39/40 players online:)(.*)$"
- "^(.*)(There are 40/40 players online:)(.*)$"
- "^(.*)(java.net.ConnectException: Connection refused (Connection refused))(.*)$"
- "^(.*)(	at java.net.PlainSocketImpl.socketConnect(Native Method))(.*)$"
- "^(.*)(	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350))(.*)$"
- "^(.*)(	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206))(.*)$"
- "^(.*)(	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188))(.*)$"
- "^(.*)(	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392))(.*)$"
- "^(.*)(	at java.net.Socket.connect(Socket.java:607))(.*)$"
- "^(.*)(	at java.net.Socket.connect(Socket.java:556))(.*)$"
- "^(.*)(	at sun.net.NetworkClient.doConnect(NetworkClient.java:180))(.*)$"
- "^(.*)(	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463))(.*)$"
- "^(.*)(	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558))(.*)$"
- "^(.*)(	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242))(.*)$"
- "^(.*)(	at sun.net.www.http.HttpClient.New(HttpClient.java:339))(.*)$"
- "^(.*)(	at sun.net.www.http.HttpClient.New(HttpClient.java:357))(.*)$"
- "^(.*)(	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226))(.*)$"
- "^(.*)(	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162))(.*)$"
- "^(.*)(	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056))(.*)$"
- "^(.*)(	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990))(.*)$"
- "^(.*)(	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570))(.*)$"
- "^(.*)(	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498))(.*)$"
- "^(.*)(	at java.net.URL.openStream(URL.java:1067))(.*)$"
- "^(.*)(	at admin.command.e.a.a(Unknown Source))(.*)$"
- "^(.*)(	at admin.command.b.run(Unknown Source))(.*)$"
- "^(.*)(	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76))(.*)$"
- "^(.*)(	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52))(.*)$"
- "^(.*)(	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149))(.*)$"
- "^(.*)(	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624))(.*)$"
- "^(.*)(	at java.lang.Thread.run(Thread.java:748))(.*)$"
