name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}Plugin
version: ${project.version}
author: novucs
load: STARTUP

commands:
  consolefilterreload:
    aliases: [cfreload, filterreload]
    permission: "consolefilter.reload"
    permission-message: "You do not have permission"

permissions:
  consolefilter.reload:
    default: op
